spring:
  cloud:
    gateway:
      routes:
        - id: url-proxy-1
          uri: lb://mail-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/coupon/(?<segment>.*),/coupon/$\{segment}  # 把/api/coupon/* 改变成 /coupon/*
server:
  port: 8088
